name: housing
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - mlflow=2.18.0
  - seaborn=0.13.2
  - matplotlib=3.9.2
  - jupyterlab=4.3.4